### ISSUE TITLE
Latest update broke chromedp

### ISSUE THREAD

**Issue by frioux** [chromedp/cdproto#1]
8d5e1d04ce19b7b3e61493418de25a281de3709d causes https://github.com/chromedp/chromedp/issues/285.  My guess is that we either need to leave a tombstone type in place or update chromedp, though clearly this is a breaking change that could break other code too.

**Comment by mvdan** [comment]
The root of the problem not here; the change in question was automated. All users of `cdproto` should pin a specific version of it, which chromedp is already doing in the master branch. Let's keep discussion in the chromedp issue.
