### ISSUE TITLE
The latest SetDownloadBehavior method is removed

### ISSUE THREAD

**Issue by penhauer-xiao** [chromedp/cdproto#10]
The latest SetDownloadBehavior method is removed. Is there an alternative method?

```
page.SetDownloadBehavior(page.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(pub.LiPath[0])
```

**Comment by ZekeLu** [comment]
`browser.SetDownloadBehavior` deprecated `page.SetDownloadBehavior`. Reference: https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior

**NOTE**: Any Issue or Pull Request intended for the `cdproto` project should be created over https://github.com/chromedp/pdlgen.

Closing.
