### ISSUE TITLE
which cdp version this cdproto repo for?

### ISSUE THREAD

**Issue by jianfengye** [chromedp/cdproto#11]
I found some event does not exist, for example:  Page.frameStoppedLoading 

So I want to know which cdp version this repo for?

**Comment by ZekeLu** [comment]
We have put both `browser_protocol.pdl` and `js_protocol.pdl` version in the commit messages. The latest commit is:

```
Updating to 92.0.4501.1_9.2.173 definitions
```

`92.0.4501.1` is the version of `Chromium` (see https://chromium.googlesource.com/chromium/src.git/+refs)
`9.2.173` is the version of `v8` (see https://chromium.googlesource.com/v8/v8/+refs)

Thanks for the question!

**NOTE**: Any Issue or Pull Request intended for the `cdproto` project should be created over https://github.com/chromedp/pdlgen.

Closing.
