### ISSUE TITLE
UnmarshalMessage panics when encountering deprecated messages

### ISSUE THREAD

**Issue by mvdan** [chromedp/cdproto#2]
For example, 8d5e1d04ce19b7b3e61493418de25a281de3709d got rid of `Page.frameScheduledNavigation` and all of its types. In `UnmarshalMessage`, that event method now doesn't fall under any of the cases, and ends up calling `json.Unmarshal(buf, v)` where `v == nil`.

The fix here is probably to modify `cdproto-gen` so that `UnmarshalMessage` handles this case gracefully:

```
diff --git a/cdproto.go b/cdproto.go
index 21f111e..fb513e9 100644
--- a/cdproto.go
+++ b/cdproto.go
@@ -2243,6 +2243,9 @@ func UnmarshalMessage(msg *Message) (interface{}, error) {

        case EventTracingTracingComplete:
                v = new(tracing.EventTracingComplete)
+
+       default:
+               return nil, errors.New("unknown or deprecated event method")
        }

        var buf easyjson.RawMessage
```

I've worked around this in chromedp v0 by capturing these events before the function is called, which is not ideal: https://github.com/chromedp/chromedp/commit/e9aa66f87e8cea7c220822b62e1ca3b90356b9cc

/cc @kenshaw

**Comment by kenshaw** [comment]
Sorry; missed this a week ago. Writing a fix now.

**Comment by kenshaw** [comment]
Fixed.

**Comment by haohanger** [comment]
@kenshaw 

got rid of Page.frameRequestedNavigation and all of its types. In UnmarshalMessage, that event method now doesn't fall under any of the cases, Page. FrameRequestedNavigation also need for processing，Like this：

switch msg.Method {
	case "Page.frameClearedScheduledNavigation",
		"Page.frameRequestedNavigation",
		"Page.frameScheduledNavigation":
		// These events are now deprecated, and UnmarshalMessage panics
		// when they are received from Chrome. For now, to avoid panics
		// and compile errors, and to fix chromedp v0 when installed via
		// 'go get -u', skip the events here.
		return nil
	}

**Comment by mvdan** [comment]
@haohanger please file a new issue, following the issue template.
