### ISSUE TITLE
Could we support go1.12?

### ISSUE THREAD

**Issue by dusmart** [chromedp/cdproto#4]
Because of some reasons, we could not update go1.12 to go1.13. Cloud we support go1.12 in some branch?

**Comment by kenshaw** [comment]
Nothing in the code is backward incompatible with Go 1.12 (in fact, I believe it should work going back to whenever `context` was added, which I think was Go 1.9. There shouldn't be a problem using/incorporating this package into earlier versions. I apologize for the fixed setting in `go.mod`, but it shouldn't matter.
