### ISSUE TITLE
prop:bug ? browser.SetDownloadBehavior vs. old page.SetDownloadBehavior

### ISSUE THREAD

**Issue by remotejob** [chromedp/cdproto#9]
github.com/chromedp/cdproto v0.0.0-20200424080200-0de008e41fa0
github.com/chromedp/chromedp v0.5.3
go version go1.14.3 linux/amd64

I change old:
`page.SetDownloadBehavior(page.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(FileDir + "/download")`

on:
`browser.SetDownloadBehavior(browser.SetDownloadBehaviorBehaviorAllow).WithDownloadPath(FileDir + "/download")`

error:

`'Browser.setDownloadBehavior' wasn't found (-32601)`

but code compiled successfully.
error during program execution  

What is wrong ?

**Comment by mvdan** [comment]
You raised this issue in https://github.com/chromedp/chromedp/issues/627 already. Please don't duplicate your issues.
